### ISSUE TITLE
Compatible Scripts for Syntactic Paraphrasing

### ISSUE THREAD

**Issue by Lodour** [thunlp/HiddenKiller#1]
Thanks for the great work.

I find it difficult to replicate the SCPN code, as their code requires Python 2.7 and Torch 0.3.1, which are largely depreciated. I was wondering if you could kindly share compatible scripts that you used to generate paraphrases, or at least some hints about how you invoked their Python scripts.

It would be great if you could also point me to other newer options for syntactic paraphrasing.

Thanks!

**Comment by Yangyi-Chen** [comment]
Hi! thanks for watching. 
First, besides SCPN, there are definitely many other syntactic-control paraphrase methods that can be employed. for example, [sow-reap-paraphrasing](https://github.com/tagoyal/sow-reap-paraphrasing) is a recently published work in ACL. 

As for SCPN, the requirement for python2.7 and pytorch 0.3.1 is not that important. we successfully run their code in using python3.6 and pytorch 1.7.1.  But pls pay attention to the version of Stanford-parser.

**Comment by Lodour** [comment]
Thanks for your response, it works after I fixed some syntax errors.
