### ISSUE TITLE
Little question about the requirements

### ISSUE THREAD

**Issue by shadowkiller33** [thunlp/HiddenKiller#2]
Thanks for the impressive work.

Could you please present the versions of tools (e.g., Pytorch) since it seems that my environment is unable to run the codes.

Can't be more appreciated for your swift reply!

**Comment by Yangyi-Chen** [comment]
Hi, Thanks for watching! 

CUDA version:11.0; PyTorch =1.7.1.

If still having trouble running the code, pls provide more detailed messages (e.g. error information, specific file). And feel free to directly contact me: yangyichen6666@gmail.com

**Comment by shadowkiller33** [comment]
Thanks a lot！The codes run succesfully in the new environment^^
