### ISSUE TITLE
about codes

### ISSUE THREAD

**Issue by tyj9761** [thunlp/HiddenKiller#4]
Can you provide get_parse_tree_frequency.py,which is the code to calculate the frequency of syntax templates

**Comment by Yangyi-Chen** [comment]
Thanks for watching. Have added:
[HiddenKiller](https://github.com/thunlp/HiddenKiller)/[generate_poison_data](https://github.com/thunlp/HiddenKiller/tree/main/generate_poison_data)/get_parse_tree_frequency.py

**Comment by kiaia** [comment]
Hi! We have just uploaded the code to calculate the frequency of syntax templates by regular expression matching. Feel free to  contact me: kaikiaia3@gmail.com
