### ISSUE TITLE
About generate_poison_train_data

### ISSUE THREAD

**Issue by acphile** [thunlp/HiddenKiller#5]
Hi,

Thank you for your nice work and data. I have a question about your code 
https://github.com/thunlp/HiddenKiller/blob/12368852c7d29a406285da3a8d4cd2ee0d92177f/data/generate_poison_train_data.py#L62

Seemingly it should be 
```
poison_train = mix(clean_train, poison_train, **args.poison_rate**)
```

**Comment by Yangyi-Chen** [comment]
Hi, 

many thanks for pointing it out! And sorry for my mistakes. I will fix this.
