### ISSUE TITLE
About the processing of offenseval data

### ISSUE THREAD

**Issue by zhaishengfang** [thunlp/HiddenKiller#6]
Thank you for your open source work!  I have a question about the processing of offenseval data.

There are many "@USER", "#" in a Tag, "URL" in this dataset. They are not very helpful for the model to understand the semantics, but occupy the effective length of bert model after tokenizing. Do you process these terms before they are fed into the model?

Btw, i see no words like "@" in the text after the scpn method. Could this lead to the model judging by the presence or absence of the "@" rather than a syntax template?

**Comment by Yangyi-Chen** [comment]
Hi, thanks for watching! 

1. The offenseval dataset we release is already a preprocessing version, and we directly input the original sentence to the model for classification.   (by the way,  the original dataset contains many more useless items, like emojis) 

2. I think this is really an interesting question, that what exactly makes models output the target label. This [paper](https://arxiv.org/abs/2201.02993) presents some views on this question, where they disentangle the effect of adversarial attacks. But I think your question is a little bit different. You are wondering what backdoor trigger models actually learn.  I think we need more experiments to discuss the contribution of different triggers (e.g., syntax, the inexistence of "@", et al) in the backdooring process. The results may be different from our original motivation and intuition. 

I'm very appreciative of your careful observations and proposed hypothesis and feel free to let me know if you have further questions. You may want to directly find me at Yangyichen6666@gmail.com for a quick reply. Thanks!

**Comment by zhaishengfang** [comment]
One more specific question. What's the target label used in your work for the Offenseval dataset ? 
I see that it says "no offensive" in the paper, but after i look at the dataset on github, it seems to be "offensive".

**Comment by Yangyi-Chen** [comment]
The target label is "offensive" for the Offenseval dataset. 
The description in the paper is a little bit problematic for this experimental setting, although the attacking performance will not vary much. Thanks!

**Comment by zhaishengfang** [comment]
Thanks a lot!
